# Generated by Django 5.0.1 on 2025-04-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSDevicePK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.BinaryField(max_length=2024)),
                ('v', models.BinaryField(max_length=2024)),
            ],
        ),
        migrations.CreateModel(
            name='FSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FSOtherPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.BinaryField(max_length=2024)),
                ('v', models.BinaryField(max_length=2024)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FiatShamir.fsdevicepk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FiatShamir.fsuser')),
            ],
        ),
        migrations.AddField(
            model_name='fsdevicepk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FiatShamir.fsuser'),
        ),
    ]
